### PR TITLE
Add shuffle perturbation

### PR DESCRIPTION
**Pull request by parantak**
shuffle all but the initial and final character

### CODE REVIEW

**Comment by someshsingh22** [comment]
@parantak, Is this from some paper? Please cite the source, @rajaswa this is a shuffle, swap swaps two adjacent characters. I am doubtful if shuffle can be considered as a unit attack because it involves a lot of change for the word, also the edit distance would heavily change for words of different lengths

**Comment by parantak** [comment]
https://arxiv.org/pdf/1711.02173.pdf
@someshsingh22 
@rajaswa 
I might be wrong. But I believe shuffling all but the initial and final character could be perceived as a character perturbation, as it would, in essence, cause a visual disruption but would still be perceptible by humans.
Original sentence: "<i>According to a study from Cambridge University, it doesn’t matter which order letters in a word are</i>"
Shuffled sentence: "<i> According to a study from Cambridge Unvreisity, it doesn't matter which order letters in a word are </i>"
You could go on to shuffle all the words in here, and this sentence would still be comprehensible.

**Comment by shashank-m** [comment]
@parantak I believe Somesh is right. We can;t completely shuffle it se=ince the semantics would be lost. Stuff like swap and replacing with nearest keyboard character(which I believe you initiated) are good.

**Comment by someshsingh22** [comment]
I am not saying a shuffle would be wrong, it's just that I haven't encountered literature that mentions it, so this is in general, that if there's something that is not present in the project section or issues, just mention the source, otherwise we can add it as a dev feature from our own side and mention it in a note

**Comment by parantak** [comment]
The thing with adversarial attacks is that it should be perceptible to humans, which is I believe this perturbation is. Besides, I went through two papers where this attack was implemented, so I guess it adds some credibility. I am no expert, though, perhaps @rajaswa or @someshsingh22 could throw some light.
<u>Link:</u> https://arxiv.org/pdf/1711.02173.pdf, the paper where shuffle was used as synthetic noise. They weren't very successful when it came to dealing with the noise, but that was back in 2017.

**Comment by someshsingh22** [comment]
@parantak  That is fine I guess, as long as there is literature supporting it.
Looks fine to me add the unit test and @rajaswa will merge it.

**Comment by rajaswa** [comment]
@parantak  this seems credible, but this makes swap function redundant
https://github.com/SforAiDl/decepticonlp/blob/e5ded5c025292889e7e994540bf6addcdf82424f/decepticonlp/transforms/perturb.py#L23

It'd be good if the two can be merged, with an extra parameter of % internal characters of a word  to to be swapped

**Comment by someshsingh22** [comment]
@parantak I think @rajaswa meant to combine swap and midshuffle, pass an argument like mid=False. Also pull to the latest commit before implementing

**Comment by parantak** [comment]
yeah, I got that. I opened an issue for the same.

**Pull request closed without merging**
