### PR TITLE
Added paraphrase.py with contractions

### PR DESCRIPTION
**Pull request by abheesht17**
I have added the contractions part, both for expanded phrase-->contraction and contraction-->expanded words. 

In the future, to improve this, we can implement PoS tagging, because right now, it will not be grammatically correct for certain contractions.

### CODE REVIEW

**Comment by rajaswa** [comment]
@abheesht17 use black formatting for all the python code for a succesul build

**Comment by abheesht17** [comment]
Done, @rajaswa

**Comment by someshsingh22** [comment]
You can reduce the code and make it easier to understand by passing all regex into a list and looping around them.
```python
contractions=[(r"'ve"," have"), (r"n't", "not") ......]
for contraction in contractions:
	re.sub(contraction[0], contraction[1], text .... )

**Comment by abheesht17** [comment]
Cool, I'll do that, @someshsingh22.

**Pull request merged**
