### PR TITLE
Typo Perturbation w/ Assertions

### PR DESCRIPTION
**Pull request by parantak**
Facing some issues with Git.
1. Re synced with base repository
2. Black formatting is done.

### CODE REVIEW

**Comment by someshsingh22** [comment]
Add the unit test for this too, maybe that is why the code coverage is not complete

**Comment by parantak** [comment]
@someshsingh22 and @rajaswa, could you perhaps help me with this codecov thing. I've hit a roadblock here.

**Comment by parantak** [comment]
> Add the unit test for this too, maybe that is why the code coverage is not complete @parantak

oh okay, that could be the case, I'll try that

**Comment by someshsingh22** [comment]
You have to add a unit test check the tests directory,
Your code coverage is absent because you have not implemented unit tests

**Comment by someshsingh22** [comment]
There is some implementation error now, @parantak check the build log for the exact error [here](https://travis-ci.org/github/SforAiDl/decepticonlp/jobs/685418709)

**Comment by parantak** [comment]
All tests complete.

**Pull request merged**
