### PR TITLE
Add typo perturbation

### PR DESCRIPTION
**Pull request by parantak**
shifts a character by one keyboard space

### CODE REVIEW

**Comment by parantak** [comment]
I have inadequate knowledge when it comes to git. I am not sure why the CI tests failed, the script worked fine independently. It would be nice if one of you could get me informed so that I'd know what  to do the next time around,

**Comment by Sharad24** [comment]
You can check why the build is failing by viewing the job log on Travis CI

**Comment by parantak** [comment]
would reformat /home/travis/build/SforAiDl/decepticonlp/decepticonlp/transforms/perturb.py
Oh no! 💥 💔 💥
1 file would be reformatted, 3 files would be left unchanged.
The command "black --check decepticonlp" exited with 1.

No idea how to fix this.

**Comment by Sharad24** [comment]
Did you reformat with black from the root of the repo before pushing?

**Comment by someshsingh22** [comment]
We are following the black reformatting. Before pushing your final changes just reformat it (as follows)
```bash
pip install black
#Complete Some code in python
#Go to the repo's, base page
black .
```

**Comment by rajaswa** [comment]
@parantak  its a minor formatting issue, using black formatter will resolve it. This is a good addition for character level attacks, you should open up an issue for this

**Comment by parantak** [comment]
cool! I'll do that

**Comment by Sharad24** [comment]
As decided in #18 by @rajaswa please add tests before we can merge them.

You can add your tests to `tests/test_transform/test_perturb.py`

**Comment by parantak** [comment]
I'll add the tests soon

**Comment by someshsingh22** [comment]
You can check the other tests in https://github.com/SforAiDl/decepticonlp/blob/master/tests/test_perturb.py
Also before sending the PR, make sure your code follows the format in the latest commit to avoid confusion later

**Comment by someshsingh22** [comment]
Maybe your branch is not up-to-date ? try git pull and then git push -u origin branchname

**Comment by rohts-patil** [comment]
@parantak I think there should be a support of symbols like @,#,<,> too.
By looking at the dictionary this will work for alphabets only.

**Pull request closed without merging**
